---
title: "Data Carpentry raster tutorial"
output: html_notebook
---

```{r}
#Housekeeping
library(tidyverse)
library(raster)
library(rgdal)
library(here)
library(reshape)
library(scales)
library(R.utils)
library(sp)
library(sf)

```

```{r}
# Intro to geospatial raster/vector data w/ R tutorial - https://datacarpentry.org/r-raster-vector-geospatial/
# Data Carpentry intro/plot/reproject raster data in R tutorial - DC data

DTM_HARV <- raster(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/DTM/HARV_dtmCrop.tif"))

DTM_hill_HARV <- raster(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/DTM/HARV_DTMhill_WGS84.tif"))

DTM_HARV_df <- as.data.frame(DTM_HARV, xy = TRUE)

DTM_hill_HARV_df <- as.data.frame(DTM_hill_HARV, xy = TRUE)

ggplot() +
     geom_raster(data = DTM_HARV_df , 
                 aes(x = x, y = y, 
                  fill = HARV_dtmCrop)) + 
     geom_raster(data = DTM_hill_HARV_df, 
                 aes(x = x, y = y, 
                   alpha = HARV_DTMhill_WGS84)) +
     scale_fill_gradientn(name = "Elevation", colors = terrain.colors(10)) + 
     coord_quickmap()

ggplot() +
geom_raster(data = DTM_HARV_df,
    aes(x = x, y = y,
    fill = HARV_dtmCrop)) +
scale_fill_gradientn(name = "Elevation", colors = terrain.colors(10)) + 
coord_quickmap()

ggplot() +
geom_raster(data = DTM_hill_HARV_df,
    aes(x = x, y = y,
    alpha = HARV_DTMhill_WGS84)) + 
    coord_quickmap()

crs(DTM_HARV)

crs(DTM_hill_HARV)

DTM_hill_UTMZ18N_HARV <- projectRaster(DTM_hill_HARV,
                                       crs = crs(DTM_HARV))

extent(DTM_hill_UTMZ18N_HARV)

extent(DTM_hill_HARV)

res(DTM_hill_UTMZ18N_HARV)

res(DTM_hill_HARV)

DTM_hill_UTMZ18N_HARV <- projectRaster(DTM_hill_HARV,
                                       crs = crs(DTM_HARV),
                                       res = 1)

DTM_hill_HARV_2_df <- as.data.frame(DTM_hill_UTMZ18N_HARV, xy = TRUE)

ggplot() +
     geom_raster(data = DTM_HARV_df , 
                 aes(x = x, y = y, 
                  fill = HARV_dtmCrop)) + 
     geom_raster(data = DTM_hill_HARV_2_df, 
                 aes(x = x, y = y, 
                   alpha = HARV_DTMhill_WGS84)) +
     scale_fill_gradientn(name = "Elevation", colors = terrain.colors(10)) + 
     coord_quickmap()
```

```{r}
# Data Carpentry raster calculations in R tutorial - DC data

GDALinfo(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/DTM/HARV_dtmCrop.tif"))

GDALinfo(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/DSM/HARV_dsmCrop.tif"))

ggplot() +
      geom_raster(data = DTM_HARV_df , 
              aes(x = x, y = y, fill = HARV_dtmCrop)) +
     scale_fill_gradientn(name = "Elevation", colors = terrain.colors(10)) + 
     coord_quickmap()

# Create Digital Surface Model (DSM) layer from intro tutorial

DSM_HARV <- raster(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/DSM/HARV_dsmCrop.tif"))

DSM_HARV_df <- as.data.frame(DSM_HARV, xy = TRUE)

ggplot() +
      geom_raster(data = DSM_HARV_df , 
              aes(x = x, y = y, fill = HARV_dsmCrop)) +
     scale_fill_gradientn(name = "Elevation", colors = terrain.colors(10)) + 
     coord_quickmap()

# Raster calculation method 1: raster math

CHM_HARV <- DSM_HARV - DTM_HARV

CHM_HARV_df <- as.data.frame(CHM_HARV, xy = TRUE)

ggplot() +
   geom_raster(data = CHM_HARV_df , 
               aes(x = x, y = y, fill = layer)) + 
   scale_fill_gradientn(name = "Canopy Height", colors = terrain.colors(10)) + 
   coord_quickmap()

ggplot(CHM_HARV_df) +
    geom_histogram(aes(layer))

# Raster calculation method 2: overlay

CHM_ov_HARV <- overlay(DSM_HARV,
                       DTM_HARV,
                       fun = function(r1, r2) { return( r1 - r2 ) })

CHM_ov_HARV_df <- as.data.frame(CHM_ov_HARV, xy = TRUE)

ggplot() +
   geom_raster(data = CHM_ov_HARV_df, 
               aes(x = x, y = y, fill = layer)) + 
   scale_fill_gradientn(name = "Canopy Height", colors = terrain.colors(10)) + 
   coord_quickmap()

writeRaster(CHM_ov_HARV, here("tutorial_data/CHM_HARV.tiff"),
            format="GTiff",
            overwrite=TRUE,
            NAflag=-9999)
```

```{r}
# Data Carpentry work with multi-band rasters in R tutorial - DC data

RGB_band1_HARV <- raster(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/RGB_Imagery/HARV_RGB_Ortho.tif"))

# band 1 = red
RGB_band1_HARV_df <- as.data.frame(RGB_band1_HARV, xy = TRUE)

ggplot() +
  geom_raster(data = RGB_band1_HARV_df,
              aes(x = x, y = y, alpha = HARV_RGB_Ortho)) + 
  coord_quickmap()

# band 2 = green
RGB_band2_HARV <- raster(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/RGB_Imagery/HARV_RGB_Ortho.tif"))

RGB_band2_HARV_df <- as.data.frame(RGB_band2_HARV, xy = TRUE)

ggplot() +
  geom_raster(data = RGB_band2_HARV_df,
              aes(x = x, y = y, alpha = HARV_RGB_Ortho)) + 
  coord_equal()

# Raster Stacks
RGB_stack_HARV <- stack(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/RGB_Imagery/HARV_RGB_Ortho.tif"))

RGB_stack_HARV@layers

RGB_stack_HARV[[2]]

RGB_stack_HARV_df <- as.data.frame(RGB_stack_HARV, xy = TRUE)

str(RGB_stack_HARV_df)

ggplot() +
  geom_histogram(data = RGB_stack_HARV_df, aes(HARV_RGB_Ortho.1)) # Plots 1st band only

ggplot() +
  geom_raster(data = RGB_stack_HARV_df,
              aes(x = x, y = y, alpha = HARV_RGB_Ortho.2)) + 
  coord_quickmap()

# Create 3-band image 
plotRGB(RGB_stack_HARV,
        r = 1, g = 2, b = 3,
        scale = 800,
        stretch = "hist") # Explore "stretch" of image over visual spectrum: "lin"/"hist"

# No data
GDALinfo(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/RGB_Imagery/HARV_Ortho_wNA.tif"))

HARV_NA <- stack(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/RGB_Imagery/HARV_Ortho_wNA.tif"))
# this file labels NAs as -9999 and they are therefore not plotted (black edges)

plotRGB(HARV_NA,
        r = 1, g = 2, b = 3) 

# RasterBrick - contains all objects in R environment instead of referencing rasters elsewhere - faster/more efficient to process
object.size(RGB_stack_HARV)

RGB_brick_HARV <- brick(RGB_stack_HARV)

object.size(RGB_brick_HARV)

plotRGB(RGB_brick_HARV)


```

```{r}
# Data Carpentry open & plot shapefiles tutorial - using {sf}

aoi_boundary_HARV <- sf::st_read(here("tutorial_data/NEON-DS-Site-Layout-Files/HARV/HarClip_UTMZ18.shp"))

st_geometry_type(aoi_boundary_HARV)

st_crs(aoi_boundary_HARV)

st_bbox(aoi_boundary_HARV)

aoi_boundary_HARV

ggplot() + 
  geom_sf(data = aoi_boundary_HARV, size = 3, color = "black", fill = "cyan1") + 
  ggtitle("AOI Boundary Plot") + 
  coord_sf()

lines_HARV <- st_read(here("tutorial_data/NEON-DS-Site-Layout-Files/HARV/HARV_roads.shp"))

point_HARV <- st_read(here("tutorial_data/NEON-DS-Site-Layout-Files/HARV/HARVtower_UTM18N.shp"))

class(lines_HARV)

class(point_HARV)

st_bbox(lines_HARV)

st_crs(lines_HARV)

st_bbox(point_HARV)
```

```{r}
# Data Carpentry explore and plot by vector layer attributes

point_HARV

ncol(lines_HARV)

names(lines_HARV)

head(lines_HARV)

lines_HARV$TYPE

levels(lines_HARV$TYPE)

# Subsetting foothpaths, boardwalks
footpath_HARV <- lines_HARV %>% 
  filter(TYPE == "footpath")
nrow(footpath_HARV)

ggplot() + 
  geom_sf(data = footpath_HARV) +
  ggtitle("NEON Harvard Forest Field Site", subtitle = "Footpaths") + 
  coord_sf()

ggplot() + 
  geom_sf(data = footpath_HARV, aes(color = factor(OBJECTID)), size = 1.5) +
  labs(color = 'Footpath ID') +
  ggtitle("NEON Harvard Forest Field Site", subtitle = "Footpaths") + 
  coord_sf()

boardwalk_HARV <- lines_HARV %>% 
  filter(TYPE == "boardwalk")
nrow(boardwalk_HARV)

ggplot() + 
  geom_sf(data = boardwalk_HARV, size = 1.5) +
  ggtitle("NEON Harvard Forest Field Site", subtitle = "Boardwalks") + 
  coord_sf()

stoneWall_HARV <- lines_HARV %>% 
  filter(TYPE == "stone wall")
nrow(stoneWall_HARV)

ggplot() +
  geom_sf(data = stoneWall_HARV, aes(color = factor(OBJECTID)), size = 1.5) +
  labs(color = 'Wall ID') +
  ggtitle("NEON Harvard Forest Field Site", subtitle = "Stonewalls") + 
  coord_sf()

# Custom plots
road_colors <- c("blue", "green", "navy", "purple")
line_widths <- c(1,2,3,4)
new_colors <- c("springgreen", "blue", "magenta", "orange")

ggplot() + 
  geom_sf(data = lines_HARV, aes(color = TYPE), size = 1.5) +
  scale_color_manual(values = new_colors) + 
  labs(color = 'Road Type') +
  theme(legend.text = element_text(size = 20), 
        legend.box.background = element_rect(size = 1)) + 
  ggtitle("NEON Harvard Forest Field Site", 
          subtitle = "Roads & Trails - Modified Legend") +
  coord_sf()

# Filter for roads where bikes/horses are allowed
class(lines_HARV$BicyclesHo)

lines_removeNA <- lines_HARV[!is.na(lines_HARV$BicyclesHo),]

lines_showHarv <- lines_removeNA %>% 
  filter(BicyclesHo == "Bicycles and Horses Allowed")

ggplot() + 
  geom_sf(data = lines_HARV) + 
  geom_sf(data = lines_showHarv, aes(color = BicyclesHo), size = 2) + 
  scale_color_manual(values = "magenta") +
  ggtitle("NEON Harvard Forest Field Site", subtitle = "Roads Where Bikes and Horses Are Allowed") +
  coord_sf()

state_boundary_US <- 
st_read(here("tutorial_data/NEON-DS-Site-Layout-Files/US-Boundary-Layers/US-State-Boundaries-Census-2014.shp"))

levels(state_boundary_US$region)

colors <- c("purple", "springgreen", "yellow", "brown", "navy")

ggplot() +
  geom_sf(data = state_boundary_US, aes(color = region), size = 1) +
  scale_color_manual(values = colors) +
  ggtitle("Contiguous U.S. State Boundaries") + 
  coord_sf()

```

```{r}
# Data Carpentry plot multiple shapefiles in R tutorial

ggplot() +
  geom_sf(data = aoi_boundary_HARV, fill = "grey", color = "grey") +
  geom_sf(data = point_HARV, aes(fill = Sub_Type), shape = 15) +
  geom_sf(data = lines_HARV, aes(color = TYPE),
          show.legend = "line", size = 1) +
  scale_color_manual(values = road_colors, name = "Line Type") +
  scale_fill_manual(values = "black", name = "Tower Location") +
  ggtitle("NEON Harvard Forest Field Site") + 
  coord_sf()

# Plot polygons by attribute
plot_locations <- st_read(here("tutorial_data/NEON-DS-Site-Layout-Files/HARV/PlotLocations_HARV.shp"))
levels(plot_locations$soilTypeOr)

blue_green <- c("blue", "darkgreen")

ggplot() + 
  geom_sf(data = lines_HARV, aes(color = TYPE), show.legend = "line", size = 1) + 
  geom_sf(data = plot_locations, aes(fill = soilTypeOr, shape = soilTypeOr),
          show.legend = 'point', colour = NA, size = 3) + 
  scale_shape_manual(name = "Soil Type", values = c(21, 22)) +
  scale_color_manual(name = "Line Type", values = road_colors,
     guide = guide_legend(override.aes = list(linetype = "solid", shape = NA))) + 
  scale_fill_manual(name = "Soil Type", values = blue_green,
     guide = guide_legend(override.aes = list(linetype = "blank", shape = c(21, 22),
     color = blue_green))) + 
  ggtitle("NEON Harvard Forest Field Site") + 
  coord_sf()

# Plot raster & vector data together
HARV_chmCrop <- st_read(here("tutorial_data/NEON-DS-Airborne-Remote-Sensing/HARV/CHM/HARV_chmCrop.tif"))

ggplot() +
  geom_raster(data = CHM_HARV_df, aes(x = x, y = y, fill = HARV_chmCrop)) +
  geom_sf(data = lines_HARV, color = "black") +
  geom_sf(data = aoi_boundary_HARV, color = "grey20", size = 1) +
  geom_sf(data = point_HARV, pch = 8) +
  ggtitle("NEON Harvard Forest Field Site w/ Canopy Height Model") + 
  coord_sf()
```

```{r}
# Data Carpentry spatial projection & CRS in R - DC data
# State boundaries read in during vector/layer lesson
state_boundary_US

ggplot() +
  geom_sf(data = state_boundary_US) +
  ggtitle("Map of Contiguous US State Boundaries") +
  coord_sf()

country_boundary_US <- st_read(here("tutorial_data/NEON-DS-Site-Layout-Files/US-Boundary-Layers/US-Boundary-Dissolved-States.shp"))

ggplot() +
  geom_sf(data = country_boundary_US, color = "gray18", size = 2) +
  geom_sf(data = state_boundary_US, color = "gray40") +
  ggtitle("Map of Contiguous US State Boundaries") +
  coord_sf()

st_crs(point_HARV)

st_crs(state_boundary_US)

st_crs(country_boundary_US)

st_bbox(point_HARV)

st_bbox(state_boundary_US)

# ggplot automatically converts all vectors/shapefiles to same crs
ggplot() +
  geom_sf(data = country_boundary_US, size = 2, color = "gray18") +
  geom_sf(data = state_boundary_US, color = "gray40") +
  geom_sf(data = point_HARV, shape = 19, color = "purple") +
  ggtitle("Map of Contiguous US State Boundaries") +
  coord_sf()

# Plotting multiple layers
NE.States.Boundary.US <- st_read(here("tutorial_data/NEON-DS-Site-Layout-Files/US-Boundary-Layers/Boundary-US-State-NEast.shp"))

ggplot() +
    geom_sf(data = NE.States.Boundary.US, aes(color ="color"), show.legend = "line") +
    scale_color_manual(name = "", labels = "State Boundary", values = c("color" = "gray18")) +
    geom_sf(data = point_HARV, aes(shape = "shape"), color = "purple") +
    scale_shape_manual(name = "", labels = "Fisher Tower", values = c("shape" = 19)) +
    ggtitle("Fisher Tower location") +
    theme(legend.background = element_rect(color = NA)) +
    coord_sf()
```

```{r}
# Data Carpentry convert from .csv to shapefile in R tutorial

plot_locations_HARV <- read.csv(here("tutorial_data/NEON-DS-Site-Layout-Files/HARV/HARV_PlotLocations.csv"))

str(plot_locations_HARV)

names(plot_locations_HARV)

# Explore geographic info in table
head(plot_locations_HARV$easting)
head(plot_locations_HARV$northing)
head(plot_locations_HARV$geodeticDa)
head(plot_locations_HARV$utmZone)

st_crs(point_HARV)

utm18nCRS <- crs(point_HARV)
utm18nCRS
class(utm18nCRS)

plot_locations_sp_HARV <- st_as_sf(plot_locations_HARV, 
                                   coords = c("easting", "northing"),
                                   crs = utm18nCRS)
st_crs(plot_locations_sp_HARV)

ggplot() +
  geom_sf(data = plot_locations_sp_HARV) +
  ggtitle("Map of Plot Locations")

ggplot() +
  geom_sf(data = aoi_boundary_HARV) +
  geom_sf(data = plot_locations_sp_HARV) +
  ggtitle("AOI Boundary Plot")

newplot_locations_HARV <- read.csv(here("tutorial_data/NEON-DS-Site-Layout-Files/HARV/HARV_2NewPhenPlots.csv"))
str(newplot_locations_HARV)

geogCRS <- st_crs(country_boundary_US)
geogCRS

newPlot.Sp.HARV <- st_as_sf(newplot_locations_HARV,
                            coords = c("decimalLon", "decimalLat"),
                            crs = geogCRS)
st_crs(newPlot.Sp.HARV)

ggplot() +
  geom_sf(data = plot_locations_sp_HARV, color = "orange") +
  geom_sf(data = newPlot.Sp.HARV, color = "lightblue") +
  ggtitle("Map of All Plot Locations")

st_write(plot_locations_sp_HARV,
         here("tutorial_data/PlotLocations_HARV.shp"),
         driver = "ESRI Shapefile")

```

```{r}
# Data Carpentry manipulate raster data in R tutorial, how to pull extent from one layer/crop others

# can't load in HARV_chmCrop layer - tif is corrupted?
ggplot() +
  geom_raster(data = CHM_HARV_df, aes(x = x, y = y, fill = layer)) + 
  scale_fill_gradientn(name = "Canopy Height", colors = terrain.colors(10)) +
  geom_sf(data = aoi_boundary_HARV, color = "blue", fill = NA) +
  coord_sf()

CHM_HARV_Cropped <- crop(x = CHM_HARV, y = aoi_boundary_HARV)
CHM_HARV_Cropped_df <- as.data.frame(CHM_HARV_Cropped, xy = TRUE)

ggplot() +
  geom_sf(data = st_as_sfc(st_bbox(CHM_HARV)), fill = "green",
          color = "green", alpha = .2) +  
  geom_raster(data = CHM_HARV_Cropped_df,
              aes(x = x, y = y, fill = layer)) + 
  scale_fill_gradientn(name = "Canopy Height", colors = terrain.colors(10)) + 
  coord_sf()

ggplot() +
  geom_raster(data = CHM_HARV_Cropped_df,
              aes(x = x, y = y, fill = layer)) + 
  geom_sf(data = aoi_boundary_HARV, color = "blue", fill = NA) + 
  scale_fill_gradientn(name = "Canopy Height", colors = terrain.colors(10)) + 
  coord_sf()

st_bbox(CHM_HARV)
st_bbox(CHM_HARV_Cropped)
st_bbox(aoi_boundary_HARV)
st_bbox(plot_locations_sp_HARV)

CHM_plots_HARVcrop <- crop(x = CHM_HARV, y = plot_locations_sp_HARV)

CHM_plots_HARVcrop_df <- as.data.frame(CHM_plots_HARVcrop, xy = TRUE)

ggplot() + 
  geom_raster(data = CHM_plots_HARVcrop_df, aes(x = x, y = y, fill = layer)) + 
  scale_fill_gradientn(name = "Canopy Height", colors = terrain.colors(10)) + 
  geom_sf(data = plot_locations_sp_HARV) + 
  coord_sf()

# Use extent() to create cropping extent/bbox
new_extent <- extent(732161.2, 732238.7, 4713249, 4713333)
class(new_extent)

CHM_HARV_manual_cropped <- crop(x = CHM_HARV, y = new_extent)
CHM_HARV_manual_cropped_df <- as.data.frame(CHM_HARV_manual_cropped, xy = TRUE)

ggplot() + 
  geom_sf(data = aoi_boundary_HARV, color = "blue", fill = NA) +
  geom_raster(data = CHM_HARV_manual_cropped_df,
              aes(x = x, y = y, fill = layer)) + 
  scale_fill_gradientn(name = "Canopy Height", colors = terrain.colors(10)) + 
  coord_sf()

# Extract raster pixel values using vector polygons - w/in AOI
tree_height <- raster::extract(x = CHM_HARV, y = aoi_boundary_HARV, df = TRUE)
str(tree_height)

ggplot() + 
  geom_histogram(data = tree_height, aes(x = layer)) +
  ggtitle("Histogram of CHM Height Values (m)") +
  xlab("Tree Height") + 
  ylab("Frequency of Pixels")

summary(tree_height$layer)

mean_tree_height_AOI <- raster::extract(x = CHM_HARV, y = aoi_boundary_HARV, fun = mean)
mean_tree_height_AOI

# Extract pixel values using x,y locations (proximity)
mean_tree_height_tower <- raster::extract(x = CHM_HARV,
                                  y = point_HARV,
                                  buffer = 20,
                                  fun = mean)
mean_tree_height_tower

mean_tree_height_plots_HARV <- raster::extract(x = CHM_HARV,
                                       y = plot_locations_sp_HARV,
                                       buffer = 20,
                                       fun = mean,
                                       df = TRUE)
mean_tree_height_plots_HARV

ggplot(data = mean_tree_height_plots_HARV, aes(ID, layer)) + 
  geom_col() + 
  ggtitle("Mean Tree Height at each Plot") + 
  xlab("Plot ID") + 
  ylab("Tree Height (m)")

```
 
```{r}
# Data Carpentry raster time series data in R tutorial - DC data

NDVI_HARV_path <- here("tutorial_data/NEON-DS-Landsat-NDVI/HARV/2011/NDVI")

all_NDVI_HARV <- list.files(NDVI_HARV_path,
                            full.names = TRUE,
                            pattern = ".tif$")
all_NDVI_HARV 

NDVI_HARV_stack <- stack(all_NDVI_HARV)
crs(NDVI_HARV_stack)
extent(NDVI_HARV_stack)
yres(NDVI_HARV_stack)
xres(NDVI_HARV_stack)

NDVI_HARV_stack_df <- as.data.frame(NDVI_HARV_stack, xy = TRUE) %>% 
  melt(id.vars = c('x', 'y')) # melt() combines multiple columns for NDVI observations into one field

ggplot() +
  geom_raster(data = NDVI_HARV_stack_df , aes(x = x, y = y, fill = value)) +
  facet_wrap(~ variable)

NDVI_HARV_stack <- NDVI_HARV_stack/10000
NDVI_HARV_stack_df <- as.data.frame(NDVI_HARV_stack, xy = TRUE) %>% 
  melt(id.vars = c('x', 'y'))

ggplot() +
  geom_raster(data = NDVI_HARV_stack_df , aes(x = x, y = y, fill = value)) +
  facet_wrap(~variable)

# weird annual pattern where NDVI spikes @ some sites @ end of year
ggplot(NDVI_HARV_stack_df) +
  geom_histogram(aes(value)) +
    facet_wrap(~variable)

har_met_daily <- read.csv(here("tutorial_data/NEON-DS-Met-Time-Series/HARV/FisherTower-Met/hf001-06-daily-m.csv"))
str(har_met_daily)

har_met_daily$date <- as.Date(har_met_daily$date, format = "%Y-%m-%d")
                             
yr_11_daily_avg <- subset(har_met_daily,
                          date >= as.Date('2011-01-01')&
                            date <= as.Date('2011-12-31'))

ggplot() +
  geom_point(data = yr_11_daily_avg, aes(jd, airt)) +
  ggtitle("Daily Mean Air Temperature",
          subtitle = "NEON Harvard Forest Field Site") +
  xlab("Julian Day 2011") +
  ylab("Mean Air Temperature (C)")

# look @ specific days to investigate weird values
RGB_277 <- stack(here("tutorial_data/NEON-DS-Landsat-NDVI/HARV/2011/RGB/277_HARV_landRGB.tif"))
RGB_277

# scale to NDVI (0-1)
RGB_277 <- RGB_277/255
RGB_277_df <- as.data.frame(RGB_277, xy = TRUE)

RGB_277_df$rgb <- with(RGB_277_df, rgb(X277_HARV_landRGB.1, X277_HARV_landRGB.2, X277_HARV_landRGB.3,1))

ggplot() +
  geom_raster(data=RGB_277_df, aes(x, y), fill=RGB_277_df$rgb) + 
  ggtitle("Julian day 277") 

#repeat for other day w/ weird data (293)
RGB_293 <- stack(here("tutorial_data/NEON-DS-Landsat-NDVI/HARV/2011/RGB/293_HARV_landRGB.tif"))
RGB_293 <- RGB_293/255
RGB_293_df <- as.data.frame(RGB_293, xy = TRUE)
RGB_293_df$rgb <- with(RGB_293_df, rgb(X293_HARV_landRGB.1, X293_HARV_landRGB.2, X293_HARV_landRGB.3,1))
ggplot() +
  geom_raster(data = RGB_293_df, aes(x, y), fill = RGB_293_df$rgb) +
  ggtitle("Julian day 293")

#both these weird days are really cloudy - hence the strange values for NDVI
```

```{r}
# Data Carpentry create publication-quality graphics tutorial

ggplot() +
  geom_raster(data = NDVI_HARV_stack_df , aes(x = x, y = y, fill = value)) +
  facet_wrap(~variable) +
  ggtitle("Landsat NDVI", subtitle = "NEON Harvard Forest") + 
  theme_void()

ggplot() +
  geom_raster(data = NDVI_HARV_stack_df , aes(x = x, y = y, fill = value)) +
  facet_wrap(~variable) +
  ggtitle("Landsat NDVI", subtitle = "NEON Harvard Forest") + 
  theme_void() + 
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

ggplot() +
  geom_raster(data = NDVI_HARV_stack_df,
              aes(x = x, y = y, fill = value)) +
  facet_wrap(~ variable) +
  ggtitle("Landsat NDVI", subtitle = "NEON Harvard Forest") + 
  theme_void() + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"), 
        plot.subtitle = element_text(hjust = 0.5))

brewer_pal(9, "Y1Gn") # doesn't work
green_colors <- c("#FFFFE5", "#F7FCB9", "#D9F0A3", "#ADDD8E", "#78C679", "#41AB5D", "#238443", "#006837", "#004529") %>% 
  colorRampPalette()

ggplot() +
  geom_raster(data = NDVI_HARV_stack_df , aes(x = x, y = y, fill = value)) +
  facet_wrap(~variable) +
  ggtitle("Landsat NDVI", subtitle = "NEON Harvard Forest") + 
  theme_void() + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"), 
    plot.subtitle = element_text(hjust = 0.5)) + 
  scale_fill_gradientn(name = "NDVI", colours = green_colors(20))

names(NDVI_HARV_stack)
raster_names <- names(NDVI_HARV_stack)
raster_names <- gsub("_HARV_ndvi_crop", "", raster_names)
raster_names
raster_names <- gsub("X", "Day", raster_names)

labels_names <- setNames(raster_names, unique(NDVI_HARV_stack_df$variable))

ggplot() +
  geom_raster(data = NDVI_HARV_stack_df , aes(x = x, y = y, fill = value)) +
  facet_wrap(~variable, labeller = labeller(variable = labels_names)) +
  ggtitle("Landsat NDVI", subtitle = "NEON Harvard Forest") + 
  theme_void() + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"), 
    plot.subtitle = element_text(hjust = 0.5)) + 
  scale_fill_gradientn(name = "NDVI", colours = green_colors(20))

ggplot() +
  geom_raster(data = NDVI_HARV_stack_df , aes(x = x, y = y, fill = value)) +
  facet_wrap(~variable, ncol = 5, labeller = labeller(variable = labels_names)) +
  ggtitle("Landsat NDVI", subtitle = "NEON Harvard Forest") + 
  theme_void() + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"), 
    plot.subtitle = element_text(hjust = 0.5)) + 
  scale_fill_gradientn(name = "NDVI", colours = green_colors(20))

raster_names <- gsub("Day", "Julian Day", raster_names)
labels_names <- setNames(raster_names, unique(NDVI_HARV_stack_df$variable))

# divergent color ramp doesn't work b/c brewer.pal() not supported
```

```{r}
# Data Carpentry derive values from raster time series tutorial
# summary statistics

avg_NDVI_HARV <- cellStats(NDVI_HARV_stack, mean)
avg_NDVI_HARV
avg_NDVI_HARV <- as.data.frame(avg_NDVI_HARV)
head(avg_NDVI_HARV)

names(avg_NDVI_HARV) <- "meanNDVI"
head(avg_NDVI_HARV)

avg_NDVI_HARV$site <- "HARV"
avg_NDVI_HARV$year <- "2011"
head(avg_NDVI_HARV)

julianDays <- gsub("X|_HARV_ndvi_crop", "", row.names(avg_NDVI_HARV))
julianDays

avg_NDVI_HARV$julianDay <- julianDays
class(avg_NDVI_HARV$julianDay)

origin <- as.Date("2011-01-01")

avg_NDVI_HARV$julianDay <- as.integer(avg_NDVI_HARV$julianDay)
avg_NDVI_HARV$Date <- origin + (avg_NDVI_HARV$julianDay - 1)
head(avg_NDVI_HARV$Date)
class(avg_NDVI_HARV$Date)

# comparing two sites - San Joaquin Experimental Range

NDVI_path_SJER <- here("tutorial_data/NEON-DS-Landsat-NDVI/SJER/2011/NDVI")
all_NDVI_SJER <- list.files(NDVI_path_SJER,
                            full.names = TRUE,
                            pattern = ".tif$")
NDVI_stack_SJER <- stack(all_NDVI_SJER)
NDVI_stack_SJER <- NDVI_stack_SJER / 10000
avg_NDVI_SJER <- as.data.frame(cellStats(NDVI_stack_SJER, mean))
names(avg_NDVI_SJER) <- "meanNDVI"
avg_NDVI_SJER$site <- "SJER"
avg_NDVI_SJER$year <- "2011"
julianDays_SJER <- gsub("X|_SJER_ndvi_crop", "", row.names(avg_NDVI_SJER))
origin <- as.Date("2011-01-01")
avg_NDVI_SJER$julianDay <- as.integer(julianDays_SJER)
avg_NDVI_SJER$Date <- origin + (avg_NDVI_SJER$julianDay - 1)
head(avg_NDVI_SJER) 

ggplot(avg_NDVI_HARV, aes(julianDay, meanNDVI)) +
  geom_point() +
  ggtitle("Landsat Derived NDVI - 2011", subtitle = "NEON Harvard Forest Field Site") +
  xlab("Julian Days") + ylab("Mean NDVI")

ggplot(avg_NDVI_SJER, aes(julianDay, meanNDVI)) +
  geom_point(colour = "SpringGreen4") +
  ggtitle("Landsat Derived NDVI - 2011", subtitle = "NEON SJER Field Site") +
  xlab("Julian Day") + ylab("Mean NDVI")

NDVI_HARV_SJER <- rbind(avg_NDVI_HARV, avg_NDVI_SJER)

ggplot(NDVI_HARV_SJER, aes(x = Date, y = meanNDVI, colour = site)) +
  geom_point(aes(group = site)) +
  geom_line(aes(group = site)) +
  ggtitle("Landsat Derived NDVI - 2011", subtitle = "Harvard Forest vs San Joaquin") +
  xlab("Date") + ylab("Mean NDVI")

# remove cloudy data (NDVI < 0.1 - usually clouds but could be real data in some places)
avg_NDVI_HARV_clean <- subset(avg_NDVI_HARV, meanNDVI > 0.1)
avg_NDVI_HARV_clean$meanNDVI < 0.1

ggplot(avg_NDVI_HARV_clean, aes(x = julianDay, y = meanNDVI)) +
  geom_point() +
  ggtitle("Landsat Derived NDVI - 2011", subtitle = "NEON Harvard Forest Field Site") +
  xlab("Julian Days") + ylab("Mean NDVI")

head(avg_NDVI_HARV_clean)
row.names(avg_NDVI_HARV_clean) <- NULL
head(avg_NDVI_HARV_clean)
write.csv(avg_NDVI_HARV_clean, file = here("tutorial_data/meanNDVI_HARV_2011.csv"))

avg_NDVI_SJER_clean <- subset(avg_NDVI_SJER, meanNDVI > 0.1)
row.names(avg_NDVI_SJER_clean) <- NULL
head(avg_NDVI_SJER_clean)
write.csv(avg_NDVI_SJER_clean, file = here("tutorial_data/meanNDVI_SJER_2011.csv"))
```