---
title: "Raster test"
output: html_notebook
---

```{r}
#Housekeeping
library(tidyverse)
library(raster)
library(rgdal)
library(here)
library(reshape)
library(scales)
library(R.utils)
library(sp)
library(sf)

```

```{r}
# Intro to geospatial data w/ R tutorial (trying w/ Rhone data) - https://datacarpentry.org/r-raster-vector-geospatial/
# Data carpentry intro to raster data in R tutorial

test_85_info <- capture.output(GDALinfo(here("rasters/pdr_eeflux/2019_08_23_et.tif")))

test_85 <- raster(here("rasters/pdr_eeflux/2019_08_23_et.tif"))

summary(test_85)

summary(test_85, maxsamp = ncell(test_85))

test_85_df <- as.data.frame(test_85, xy = TRUE)

str(test_85_df)

ggplot() +
  geom_raster(data = test_85_df,
              aes(x = x,
                  y = y,
                  fill = X2019_08_23_et)) +
  scale_fill_viridis_c(
    na.value = "deeppink" # Set display of NAs
  ) +
  coord_quickmap()

# Check coordinate reference system
crs(test_85)

test_85 <- setMinMax(test_85)

minValue(test_85)

maxValue(test_85)

# How many bands?
nlayers(test_85)

# Make a histogram of raster data
ggplot() +
  geom_histogram(data = test_85_df,
                 aes(X2019_08_23_et))

```

```{r}
# Data Carpentry plot raster data in R tutorial

test_85_df <- test_85_df %>% 
  mutate(eeflux_et = cut(X2019_08_23_et, breaks = 3))

ggplot() +
  geom_bar(data = test_85_df, aes(eeflux_et))

unique(test_85_df$eeflux_et)

test_85_df %>% 
  group_by(eeflux_et) %>% 
  count()

# Making your own custom breaks
custom_bins <- c(0,3,6,11)

test_85_df <- test_85_df %>% 
  mutate(eeflux_et2 = cut(X2019_08_23_et, breaks = custom_bins))

unique(test_85_df$eeflux_et2)

ggplot() +
  geom_bar(data = test_85_df, aes(eeflux_et2))

test_85_df %>% 
  group_by(eeflux_et2) %>% 
  count()

ggplot() +
  geom_raster(data = test_85_df,
              aes(x = x,
                  y = y,
                  fill = eeflux_et2)) +
  coord_quickmap() +
  theme(axis.title = element_blank()) +
  scale_fill_manual(values = terrain.colors(4),
                    name = "Evapotranspiration")

terrain.colors(4) # Built-in terrain colors

# Try w/ chirps data
chirps_test <- raster(x = here("rasters/chirps/chirps-v2.0.1990.07.16.tif"))

chirps_test_df <- as.data.frame(chirps_test, xy = TRUE)

chirps_test_tbl <- as_tibble(chirps_test_df) %>% 
  filter(chirps.v2.0.1990.07.16 != "-9999") %>% 
  filter(x >= 4) %>% 
  filter(x <= 7) %>% 
  filter(y >= 43) %>% 
  filter(y <= 47)

ggplot() +
  geom_raster(data = chirps_test_tbl,
              aes(fill = chirps.v2.0.1990.07.16,
                  x = x,
                  y = y)) +
  coord_quickmap() +
  theme(axis.title = element_blank())


```


```{r}
# Data Carpentry reproject raster tutorial - Rhone data https://datacarpentry.org/r-raster-vector-geospatial/03-raster-reproject-in-r/index.html

eeflux_1985 <- raster(here("rasters/pdr_eeflux/1985_07_08_et.tif"))

chirps_1985 <- raster(x = here("rasters/chirps/chirps-v2.0.2017.04.16.tif"))
                      #xmn = 4,
                      #xmx = 6,
                      #ymn = 43,
                      #ymx = 47) # Lat/long bounding box for all 3 of Bryn's sites - doesn't change anything

chirps_1985_utm <- projectRaster(from = chirps_1985, # This seems to work to snap chirps to eeflux
                                 to = eeflux_1985,
                                 alignOnly = TRUE)
# Specifying individual attributes from eeflux - not necessary?
                                #crs = crs(eeflux_1985),
                                #extent = extent(eeflux_1985)
                                #res = res(eeflux_1985))

eeflux_1985_df <- as.data.frame(eeflux_1985, xy = TRUE) %>% 
  mutate(mmh2o = X1985_07_08_et)

chirps_1985_df <- as.data.frame(chirps_1985_utm, xy = TRUE) %>% 
  mutate(mmh2o = chirps.v2.0.2017.04.16)

# Checking coordinates, extent
crs(eeflux_1985)

res(eeflux_1985)

crs(chirps_1985_utm)

res(chirps_1985_utm)

# Another command to get crs/projection: proj4string(eeflux_1985)

extent(eeflux_1985)

extent(chirps_1985_utm)

# Checking to see if reprojection worked:
ggplot() +
  geom_raster(data = chirps_1985_df,
              aes(x = x,
                  y = y,
                  fill = mmh2o)) +
  coord_quickmap() #+
  theme(axis.title = element_blank()) +
  scale_fill_manual(values = terrain.colors(4),
                    name = "Precipitation")
```


```{r}
# Data Carpentry raster calculations in R tutorial (https://datacarpentry.org/r-raster-vector-geospatial/04-raster-calculations-in-r/index.html)

water_use_df <- eeflux_1985_df - chirps_1985_df

water_use_df <- as.data.frame(water_use)

ggplot() +
  geom_raster(data = water_use_df,
              aes(x = x,
                  y = y,
                  fill = layer)) +
  scale_fill_gradientn(name = "Water use",
                       colors = terrain.colors(10)) +
  coord_quickmap()
```


```{r}
# Data Carpentry raster time series data in R tutorial - Rhone data
raster_test_path <- here("rasters/chirps/1985")

raster_pdr_all <- list.files(path = raster_test_path,
                         full.names = TRUE,
                         pattern = ".tif$")

raster_pdr_all

stack <- stack(raster_pdr_all)

crs(stack)

stack_df <- as.data.frame(stack, xy = true)
```

 
 