---
title: "raster_calc_2"
output: html_document
---

# RMD for running simultaneous CHIRPS processing

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Housekeeping
library(tidyverse)
library(raster)
library(rgdal)
library(here)
library(reshape)
library(scales)
library(R.utils)
library(sp)
library(sf)
library(parallel)
library(lubridate)
library(lfstat)
library(stringr)
```


``` {r}
chirps.clipped <- list.files(here('rasters/chirps-clipped'),
                             full.names = TRUE)

# Function to stack chirps by year, crop to pdr valleys

pdr.valley.shp <- sf::st_read(here("rasters/bbox/pdr_bbox/bd_foret_pdr.shp")) #%>% 
  st_transform(crs = crs(eeflux_temp))
# Use sf package, readOGR gives weird file structure, sf should work as crop()
# Convert shp from LCC to UTM (eeflux) - don't have to reproject chirps (but clipped rasters are already in lcc!)
  
isp.valley.shp <- sf::st_read(here("rasters/bbox/isp_bbox/bd_foret_isp.shp"))

brc.valley.shp <- sf::st_read(here("rasters/bbox/brc_bbox/bd_foret_brc.shp"))

brc.valley.shp2 <- readOGR( 
  dsn= here("rasters/bbox/brc_bbox/bd_foret_brc.shp"), 
  #layer="bd_foret_brc",
  verbose=FALSE
) # From https://www.r-graph-gallery.com/168-load-a-shape-file-into-r.html

# Set to updated valley mask
eeflux_temp <- raster(here('rasters/eeflux/ISP/2020-08-27-ET-ISP.tif')) %>% 
  projectRaster(crs = crs(isp.valley.shp),
                extent = extent(isp.valley.shp)) %>% 
  raster::mask(mask = isp.valley.shp)

# Create second mask to run simultaneously on anvil
eeflux_temp_brc <- raster(here('rasters/eeflux/BRC/2020-07-26-ET-BRC.tif')) %>% 
  projectRaster(crs = crs(brc.valley.shp2),
                extent = extent(brc.valley.shp2)) %>% 
  raster::mask(mask = brc.valley.shp2)

eeflux_temp_brc2 <- raster(here('rasters/bbox/brc_bbox/brc_crop.tif'))

writeRaster(eeflux_temp_brc, here("rasters/bbox/brc_bbox/brc_crop2.tif"), format = "GTiff")
  
chirps.clipped <- list.files(here('rasters/chirps-clipped'),
                             full.names = TRUE)

crs(raster(here('rasters/chirps-clipped/chirps-v2.0.2020.06.30-clipped.tif')))

# This command returns raster_list df w/ file path + water year
raster_df <- data.frame(f = chirps.clipped) %>% # Take chirps.clipped, give name f
  mutate(wateryear = lfstat::water_year(x =
    lubridate::ymd(
      str_extract(chirps.clipped, pattern = "[0-9]{4}\\.[0-9]{2}\\.[0-9]{2}")),
    origin = 'usgs'))

class(raster_df) # Want to feed raster a character vector (filenames)

wy1981 <- raster_df %>% 
  filter(wateryear == 1981) %>% 
  dplyr::select(-wateryear) %>% 
  .$f #. says take object piped in and give column f
  
x = wy1981$f

water_years <- c(1981:2020)

crop_stack <- function(y){
  
  for (y in water_years){
    
    message('Year is now ', y)
  
    wy <- raster_df %>% 
      filter(wateryear == y) %>%
      dplyr::select(-wateryear) %>% 
      .$f %>% 
      as.vector()
    
  suppressWarnings({ # This says run wystack, and don't give crs warnings (will run faster)
      wystack <- raster::stack(wy)
    })
  
    wystack_2 <- projectRaster(wystack, to = eeflux_temp_brc2) # converted eeflux to lcc proj above
    
    wystack_3 <- mask(wystack_2, mask = brc.valley.shp2) # change for new site
    
    wy_total <- wystack_3 %>% calc(fun = sum, na.rm = TRUE)
    
    # Change for new site
    writeRaster(wy_total,
                filename = here('rasters/chirps-wy/chirps-brc', 
                                paste("brc_chirps_", y, ".tif", sep = '')),
                overwrite = TRUE)
  
  }
return(plot(wystack_2))
}
    
read_test <- raster(here('rasters/chirps-wy/chirps-pdr/pdr_chirps_1981.tif'))

extent_test <- projectRaster(raster(here('rasters/chirps-clipped/chirps-v2.0.2020.06.30-clipped.tif')),
                             to = eeflux_temp)

plot(wy_total)

    #outfile <- here('rasters/chirps-wy/chirps-pdr', 'chirps-pdr-wy'y)
  ##outfile.base <- chr(y)
  ##outfile <- here('rasters/chirps-wy/chirps-pdr',outfile.base)


stack_test <- raster::stack(wy1981)
res(stack_test) <- 30
crop(wy-stack, y = pdr.valley.shp, overwrite = TRUE)
  #wy-total <- wy-stack %>% 
    #calc(year, fun = sum, na.rm = TRUE)

mclapply(water_years,
         crop_stack,
         mc.silent = FALSE)

crop_stack(1981)

```